services:
  db:
    image: postgres:18
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:7-alpine

  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A config worker --loglevel=info
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
