# Generated by Django 6.1.2 on 2026-10-10 13:42

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_workspaceinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workspaceinvitation',
            index=models.Index(fields=['workspace', '-created_at'], name='ws_inv_workspace_created_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceinvitation',
            index=models.Index(django.db.models.functions.text.Lower('email'), models.F('status'), models.OrderBy(models.F('created_at'), descending=True), name='ws_inv_email_status_idx'),
        ),
    ]
