from django.urls import path

from .views import (
    MyWorkspaceInvitationListView,
    WorkspaceDetailView,
    WorkspaceInvitationAcceptView,
    WorkspaceInvitationCancelView,
    WorkspaceInvitationListCreateView,
    WorkspaceLeaveView,
    WorkspaceListCreateView,
    WorkspaceMemberAddView,
    WorkspaceMemberListView,
    WorkspaceMemberRemoveView,
    WorkspaceMemberRoleUpdateView,
    WorkspaceTransferOwnershipView,
)


urlpatterns = [
    path(
        "",
        WorkspaceListCreateView.as_view(),
        name="workspace-list-create",
    ),
    path(
        "invitations/pending/",
        MyWorkspaceInvitationListView.as_view(),
        name="my-workspace-invitation-list",
    ),
    path(
        "invitations/<uuid:token>/accept/",
        WorkspaceInvitationAcceptView.as_view(),
        name="workspace-invitation-accept",
    ),
    path(
        "<int:pk>/",
        WorkspaceDetailView.as_view(),
        name="workspace-detail",
    ),
    path(
        "<int:workspace_id>/members/",
        WorkspaceMemberListView.as_view(),
        name="workspace-member-list",
    ),
    path(
        "<int:workspace_id>/members/<int:membership_id>/role/",
        WorkspaceMemberRoleUpdateView.as_view(),
        name="workspace-member-role-update",
    ),
    path(
        "<int:workspace_id>/members/<int:membership_id>/",
        WorkspaceMemberRemoveView.as_view(),
        name="workspace-member-remove",
    ),
    path(
        "<int:workspace_id>/transfer-ownership/",
        WorkspaceTransferOwnershipView.as_view(),
        name="workspace-transfer-ownership",
    ),
    path(
        "<int:workspace_id>/leave/",
        WorkspaceLeaveView.as_view(),
        name="workspace-leave",
    ),
    path(
        "<int:workspace_id>/members/add/",
        WorkspaceMemberAddView.as_view(),
        name="workspace-member-add",
    ),
    path(
        "<int:workspace_id>/invitations/",
        WorkspaceInvitationListCreateView.as_view(),
        name="workspace-invitation-list-create",
    ),
    path(
        "<int:workspace_id>/invitations/<int:invitation_id>/cancel/",
        WorkspaceInvitationCancelView.as_view(),
        name="workspace-invitation-cancel",
    ),
]
